<a href="https://colab.research.google.com/github/Supritha04/Pytorch/blob/main/DAY2withPyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###**DAY 2**


###Random Tensors

Many nueral networks start with random numbers => look at the data => update random numbers => look at data => update random numbers

In [1]:
import torch as t
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
random_t=t.rand(1,10,9)
random_t

tensor([[[0.8868, 0.7230, 0.7606, 0.6053, 0.9847, 0.1732, 0.6289, 0.3850,
          0.7425],
         [0.5490, 0.1107, 0.8617, 0.1667, 0.7492, 0.7772, 0.5701, 0.7652,
          0.1667],
         [0.0364, 0.6699, 0.9535, 0.6355, 0.5908, 0.0549, 0.7002, 0.8379,
          0.8038],
         [0.7806, 0.7115, 0.4309, 0.1521, 0.1587, 0.1079, 0.3260, 0.1435,
          0.5450],
         [0.3310, 0.3620, 0.9415, 0.8230, 0.3706, 0.1067, 0.1352, 0.8995,
          0.9423],
         [0.6304, 0.7390, 0.4892, 0.6240, 0.1899, 0.2608, 0.3012, 0.7773,
          0.8345],
         [0.6880, 0.4832, 0.4458, 0.8263, 0.4671, 0.8419, 0.7003, 0.8654,
          0.8361],
         [0.7409, 0.5649, 0.9472, 0.5068, 0.3371, 0.0417, 0.1996, 0.7287,
          0.7210],
         [0.9981, 0.2908, 0.2929, 0.6948, 0.5706, 0.6820, 0.6916, 0.5946,
          0.2445],
         [0.0334, 0.2403, 0.2919, 0.1739, 0.1455, 0.7722, 0.4724, 0.6067,
          0.8435]]])

In [2]:
random_t=t.rand(4,4)
random_t

tensor([[0.5748, 0.8304, 0.9551, 0.5142],
        [0.7988, 0.6620, 0.2216, 0.7629],
        [0.2479, 0.2388, 0.3136, 0.8710],
        [0.0991, 0.4432, 0.7211, 0.9137]])

In [3]:
random_t.ndim

2

Creating a random tensor with similar shape to an image tensor

In [9]:
ran_img=t.rand(size=(224,224,3))
print(ran_img.shape,ran_img.ndim)

torch.Size([224, 224, 3]) 3


###Zeros and Ones

Creating tensors of all zeros

In [10]:
z=t.zeros(size=(4,4))
z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Creating tensors of one

In [14]:
o=t.ones(3,3)  #"size=" can be written or we can directly mention size
o

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Datatype of tensors

In [15]:
o.dtype

torch.float32

In [16]:
random_t.dtype

torch.float32

###Creating a range of tensors and tensors-like

In [18]:
t.range(0,5)

<ipython-input-18-367ff17e7ce4>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  t.range(0,5)


tensor([0., 1., 2., 3., 4., 5.])

In [20]:
t.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arange_with_step=t.arange(start=2,end=1000,step=77)
arange_with_step

tensor([  2,  79, 156, 233, 310, 387, 464, 541, 618, 695, 772, 849, 926])

Creating tensors like

In [23]:
zeroes=t.zeros_like(arange_with_step)
zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor Datatypes

In [24]:
f32t=t.tensor([3.0,10.0,9,0],dtype=None)
f32t

tensor([ 3., 10.,  9.,  0.])

In [25]:
f32t.dtype

torch.float32

In [27]:
#Changing default datatype
f16t=t.tensor([3.0,10.0,9,0],dtype=t.float16)
print(f16t)
f16t.dtype

tensor([ 3., 10.,  9.,  0.], dtype=torch.float16)


torch.float16

In [29]:
par=t.tensor([4.0,7.0,0],
              dtype=None,
              device=None,
              requires_grad=False)
par

tensor([4., 7., 0.])

Tensors with no right datatype, no right shape and with no right device are 3 big errors what we run with PyTorch

In [30]:
f16t=f32t.type(t.float16)
f16t

tensor([ 3., 10.,  9.,  0.], dtype=torch.float16)

In [33]:
f=f16t*f32t
f

tensor([  9., 100.,  81.,   0.])

In [34]:
f.dtype

torch.float32