<a href="https://colab.research.google.com/github/Supritha04/Pytorch/blob/main/DAY3withPyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### DAY 3

In [1]:
import torch as t
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

###Getting information from tensors (tensor attributes)

Datatype => not right => tensor.datatype

Shape => not right => tensor.shape

Device => not right => tensor.device

In [2]:
tens=t.rand(3,4)
tens

tensor([[0.3350, 0.8070, 0.2417, 0.1242],
        [0.0341, 0.0339, 0.9702, 0.7917],
        [0.8012, 0.9054, 0.0519, 0.9080]])

In [3]:
print(tens)
print("datatype : ",tens.dtype)
print("shape : ",tens.shape)
print("device : ",tens.device)

tensor([[0.3350, 0.8070, 0.2417, 0.1242],
        [0.0341, 0.0339, 0.9702, 0.7917],
        [0.8012, 0.9054, 0.0519, 0.9080]])
datatype :  torch.float32
shape :  torch.Size([3, 4])
device :  cpu


###Manipulating Tensors (tensor operations)

Operations include:

* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplication

In [7]:
# tensor creation and addition
tensor=t.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [8]:
# multiplication
tensor*10

tensor([10, 20, 30])

In [9]:
# subtraction
tensor-10

tensor([-9, -8, -7])

In [13]:
# divisiom
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [12]:
# using built-in function
print(t.mul(tensor,10))
print(t.add(tensor,10))

tensor([10, 20, 30])
tensor([11, 12, 13])


### Matrix multiplication

Two ways to perform:
* Element-wise multiplication
* Matrix multiplication (dot product)

Rules to matrix multiplication
* To multiply inner dimensions must match
* Resulting matrix has shape of outer dimension

In [20]:
# we will get an error when we multilpy 2 matrices of different shape
t.matmul(t.rand(2,3),t.rand(2,3))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [22]:
t.matmul(t.rand(3,2),t.rand(2,3))

tensor([[0.2922, 0.7427, 0.5002],
        [0.1205, 0.1564, 0.1665],
        [0.2649, 0.4892, 0.4046]])

In [14]:
# Element wise
print(tensor,"*",tensor)
print(tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
tensor([1, 4, 9])


In [15]:
# Matrix multiplication
t.matmul(tensor,tensor)

tensor(14)

In [18]:
tensor@tensor

tensor(14)

In [16]:
# by hand
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 2.38 ms, sys: 0 ns, total: 2.38 ms
Wall time: 2.45 ms


In [17]:
%%time
t.matmul(tensor,tensor)

CPU times: user 125 µs, sys: 0 ns, total: 125 µs
Wall time: 131 µs


tensor(14)

### One of the most common errors in deep learning is shape errors

In [24]:
#Shapes for matrix multiplication
ten_A = t.tensor([[1,2],[3,4],[5,6]])
ten_B=t.tensor([[7,10],[8,11],[9,12]])
#how to correct the dimensions when inner dimensions are not same
# matmul=mm
t.mm(ten_A,ten_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix we use transpose

In [26]:
print(ten_B.T,ten_B.T.shape)
print(ten_B,ten_B.shape)

tensor([[ 7,  8,  9],
        [10, 11, 12]]) torch.Size([2, 3])
tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]]) torch.Size([3, 2])


In [27]:
t.mm(ten_A,ten_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [28]:
t.mm(ten_A,ten_B.T).shape

torch.Size([3, 3])

### Tensor Aggregation i.e min,max,mean,sum etc

In [30]:
x=t.arange(0,50,5)
x

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [34]:
# min
t.min(x),x.min()

(tensor(0), tensor(0))

In [35]:
#max
t.max(x),x.max()

(tensor(45), tensor(45))

In [36]:
#sum
t.sum(x),x.sum()

(tensor(225), tensor(225))

In [39]:
# For mean datatype must be float or long else we will get an error for wrong datatype
t.mean(x.type(t.float32)),x.type(t.float32).mean()

(tensor(22.5000), tensor(22.5000))