<a href="https://colab.research.google.com/github/Supritha04/Pytorch/blob/main/DAY4_3withPyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Day4_3 Excercise

In [1]:
import torch as t
import numpy as np

### 1. Creating a random tensor of shape(7,7)

In [4]:
rt=t.rand(7,7)
print(rt)

tensor([[0.1503, 0.4697, 0.7025, 0.8417, 0.5644, 0.1725, 0.6065],
        [0.7304, 0.3348, 0.0547, 0.5455, 0.0254, 0.2443, 0.6253],
        [0.8699, 0.2439, 0.6019, 0.8283, 0.9492, 0.8377, 0.5708],
        [0.7256, 0.1890, 0.0156, 0.9410, 0.5448, 0.1695, 0.3351],
        [0.4069, 0.8980, 0.9807, 0.8416, 0.3315, 0.4566, 0.1129],
        [0.2086, 0.8026, 0.5497, 0.8119, 0.2169, 0.3110, 0.0540],
        [0.9250, 0.6819, 0.7341, 0.6490, 0.7592, 0.0344, 0.8357]])


### 2. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [6]:
rt1=t.rand(7,7)
rt2=t.rand(1,7)
rtm=t.matmul(rt1,rt2.T)
rtm

tensor([[1.7325],
        [1.9378],
        [1.7859],
        [2.1021],
        [0.9307],
        [1.9536],
        [1.1456]])

### 3. Set the random seed to 0 and do exercises 2 & 3 over again.

In [7]:
random_seed=0
t.manual_seed(random_seed)
print(t.rand(7,7))
t.manual_seed(random_seed)
t.matmul(t.rand(7,7),t.rand(1,7).T)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])