<a href="https://colab.research.google.com/github/Supritha04/Pytorch/blob/main/DAY4_2withPyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###*DAY4_2*

In [1]:
import torch as t
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### PyTorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library and because of this, PyTorch has functionality to interact with it
* Data in NumPy, want in PyTorch -> `t.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `t.Tensor.numpy()`

In [2]:
# NumPy to Tensor
array=np.arange(1.0,8.0)
tensor=t.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [3]:
array.dtype,tensor.dtype

(dtype('float64'), torch.float64)

In [4]:
tensor=t.from_numpy(array).type(t.float32)

In [5]:
tensor

tensor([1., 2., 3., 4., 5., 6., 7.])

In [6]:
tensor.dtype

torch.float32

In [7]:
# Changing value of array
array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [9]:
# Tensor to NumPy
ten=t.ones(7)
npten=ten.numpy()
ten,npten

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [10]:
npten.dtype

dtype('float32')

In [11]:
# Changing the tensor
ten=ten+1
ten,npten

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproductability (trying to take random out of random)

start with random numbers -> tensor operations -> update random numbers to try and make them of the data -> again....

In [14]:
t.rand(3,3)

tensor([[0.7981, 0.2389, 0.9213],
        [0.6517, 0.8027, 0.2668],
        [0.4921, 0.3639, 0.8158]])

To reduce randomness in nueral network, PyTorch comes with concept of a **random seed**

In [15]:
ra=t.rand(3,4)
rb=t.rand(3,4)
print(ra)
print(rb)
print(ra==rb)

tensor([[0.6908, 0.9186, 0.8290, 0.7891],
        [0.0189, 0.1132, 0.5608, 0.8769],
        [0.6212, 0.2307, 0.7404, 0.5831]])
tensor([[0.9255, 0.4733, 0.5054, 0.9528],
        [0.4058, 0.5880, 0.4255, 0.7011],
        [0.9344, 0.7703, 0.8245, 0.5066]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [17]:
rs=42
t.manual_seed(rs)
rtc=t.rand(3,4)
t.manual_seed(rs)
rtd=t.rand(3,4)
print(rtc)
print(rtd)
print(rtc==rtd)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and PyTorch objects on GPU

GPU = fastest computation on numbers

### 1. Getting a GPU

1. Easiest
2. Use your own GPU
3. Use cloud computing

In [1]:
!nvidia-smi

Sun Feb 11 12:21:48 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   57C    P8              12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU access with PyTorch

In [2]:
import torch
torch.cuda.is_available()

True

In [3]:
# Setup device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

In [5]:
# Create a tensor (default on the CPU)
tensor=torch.tensor([1,2,3])

print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [6]:
# Move tensor to GPU (if available)
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the GPU

In [7]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [8]:
# To fix the GPU tensor with NumPy issues we can first set it to the CPU
tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [9]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')