<a href="https://colab.research.google.com/github/Supritha04/Pytorch/blob/main/DAY4_1withPyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###DAY4_1

In [1]:
import torch as t
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Positional min and max

In [4]:
x=t.arange(5,500,10)
x

tensor([  5,  15,  25,  35,  45,  55,  65,  75,  85,  95, 105, 115, 125, 135,
        145, 155, 165, 175, 185, 195, 205, 215, 225, 235, 245, 255, 265, 275,
        285, 295, 305, 315, 325, 335, 345, 355, 365, 375, 385, 395, 405, 415,
        425, 435, 445, 455, 465, 475, 485, 495])

In [5]:
x.argmin()

tensor(0)

In [6]:
x[0]

tensor(5)

In [7]:
x.argmax()

tensor(49)

In [8]:
x[49]

tensor(495)

###Reshaping, stacking, squeezing and unsqueezing

* Reshaping - reshapes tensor to a defined shape
* View - return a view of an input tensor of certain shape
* Stacking - Combine multipletensors on top of each other
* Squeeze - remove all 1 dimension from a tensor
* Unsqueeze - add 1 to dimension to target tensor
* Permute - return a view of input with dimensions permuted (swapped) in a certain way

In [9]:
x=t.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [10]:
# Reshape
x_reshape=x.reshape(1,9)
x_reshape,x_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [11]:
x_reshape=x.reshape(9,1)
x_reshape,x_reshape.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [12]:
# Change the view
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [13]:
# Changing z changes x
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [14]:
# Stack tensors on top of each other
x_stack=t.stack([x,x,x,x])
x_stack

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [15]:
x_stack=t.stack([x,x,x,x],dim=1)
x_stack

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [16]:
# Squeeze and Unsqueeze
x_reshape

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [17]:
x_reshape.shape

torch.Size([9, 1])

In [18]:
x_reshape.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [20]:
x_reshape.squeeze().shape

torch.Size([9])

In [21]:
x_s=x_reshape.squeeze()

In [23]:
x_s,x_s.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [26]:
x_s.unsqueeze(dim=0),x_s.unsqueeze(dim=0).shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [27]:
x_s.unsqueeze(dim=1),x_s.unsqueeze(dim=0).shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([1, 9]))

In [28]:
# Permute
x=t.randn(2,3,5)
x,x.size()

(tensor([[[ 0.6327, -0.3627,  1.0791, -0.3652, -0.8523],
          [-1.3567, -0.1719,  0.8450, -1.0338,  2.5362],
          [ 0.2181,  0.7601, -1.1201, -2.3380,  2.1630]],
 
         [[ 1.2990,  0.5316, -2.4838, -1.0893,  0.7219],
          [-0.7248, -0.9829,  1.8118, -0.9757,  1.3217],
          [-1.6498,  1.2776, -0.9798,  0.0814,  0.6683]]]),
 torch.Size([2, 3, 5]))

In [29]:
t.permute(x,(2,0,1)),t.permute(x,(2,0,1)).shape

(tensor([[[ 0.6327, -1.3567,  0.2181],
          [ 1.2990, -0.7248, -1.6498]],
 
         [[-0.3627, -0.1719,  0.7601],
          [ 0.5316, -0.9829,  1.2776]],
 
         [[ 1.0791,  0.8450, -1.1201],
          [-2.4838,  1.8118, -0.9798]],
 
         [[-0.3652, -1.0338, -2.3380],
          [-1.0893, -0.9757,  0.0814]],
 
         [[-0.8523,  2.5362,  2.1630],
          [ 0.7219,  1.3217,  0.6683]]]),
 torch.Size([5, 2, 3]))

### Indexing (selecting data from tensors)

In [30]:
x=t.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [31]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [34]:
x[0][0],x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [35]:
x[0][0][0]

tensor(1)

In [36]:
# Using :
x[:,0]

tensor([[1, 2, 3]])

In [37]:
x[:,:,1]

tensor([[2, 5, 8]])

In [38]:
x[:,1,1]

tensor([5])

In [39]:
print(x[0][2][2])
print(x[:,:,2])

tensor(9)
tensor([[3, 6, 9]])
