<a href="https://colab.research.google.com/github/Supritha04/Pytorch/blob/main/D1/Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Starting Pytorch fundamentals

In [2]:
import torch
print(torch.__version__)

2.1.0+cu121


In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Introduction to Tensors

In [4]:
#creating tensors

#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
#tensor as int
scalar.item()

7

In [7]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim
# dimensions = no.of pairs of square brackets

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#matrix
matrix= torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
matrix.ndim

2

In [12]:
matrix[0]

tensor([7, 8])

In [13]:
matrix[1]

tensor([ 9, 10])

In [17]:
 matrix.shape

torch.Size([2, 2])

In [18]:
#tensor
TENSOR=torch.tensor([[[1,2,3],[3,5,6],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 5, 6],
         [2, 4, 5]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 5, 6],
        [2, 4, 5]])

In [22]:
# another example of tensor
t=torch.tensor([[1,2],[3,4],[5,6],[7,8]])
t

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [23]:
t.shape

torch.Size([4, 2])

In [24]:
t1=torch.tensor([[[1,2],[3,4],[5,6],[7,8]]])
t1

tensor([[[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]])

In [25]:
t1.shape

torch.Size([1, 4, 2])

CONCLUSION: shape of tensors completely depends upon the pairs of "[" brackets.